name: suivi_poste
description: Suivi Poste TN

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  permission_handler: '^3.0.0'
  cupertino_icons: ^0.1.2
  flutter_barcode_scanner: ^0.1.3
  html: ^0.14.0+2
  http: ^0.12.0+2
  sqflite:
  path_provider:
  intl: ^0.15.8
  splashscreen:
  url_launcher: ^5.1.0
  flutter_launcher_icons: "^0.7.2"
  dynamic_theme: ^1.0.1
  feather_icons_flutter: ^4.7.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/icon.png"
  image_path_android: "assets/icon.png"

flutter:

  uses-material-design: true


  assets:
    - assets/mail.png
    - assets/search.png
    - assets/num_envoi.jpg
    - assets/scan.gif
    
  fonts:
    - family: Airbnb
      fonts:
        - asset: fonts/AirbnbCereal-Light.ttf
        - asset: fonts/AirbnbCereal-Bold.ttf
          weight: 700
